### ISSUE TITLE
Breaking change from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by Quizart** [roryrjb/crypto-json#3]
We'd been using 2.0.0 without issue for some time.

When I went to update our packages, I updated this to 2.0.1 - now it isn't working.

`{cipher: 'camellia-128-cbc', passKey: 'xxx', encoding: 'hex'};`` is our setup`

This is the error I get:

`error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length`

Perhaps a dependency needs to be updated?

Reverting back to 2.0.0 fixed the issue, which I will do in the meantime.

**Comment by roryrjb** [comment]
Hey @Quizart not sure about this. I tested with that cipher and didn't get any errors, but without seeing more of your implementation (which you may be unable to share) I cannot know for sure what's going on. One thing I did notice is that the README has references to a `cipher` property when it should have been `algorithm`. I've just fixed this in `2.0.2`.

Other than that, just to clarify, and this may already be clear to you (and wouldn't explain the discrepancy between `2.0.0` and `2.0.1`) but in your short example it should be like this:

```
cryptoJSON.encrypt(someObject, 'xxx', {algorithm: 'camellia-128-cbc', encoding: 'hex'});
```

...actually I've just realised that this is a _decrypt_ error... so perhaps if you were using the `cipher` property to specify `'camellia-128-cbc'` on a encrypted equivalent object it'd actually be try to decrypt using `aes-256`, the default. Can you check this and let me know? Cheers! :beers:
