### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by roryrjb** [roryrjb/crypto-json#8]
I don't use this module anymore, and to be honest I don't even use Node.js or GitHub much anymore, and I don't have the time to update it, review issues or pull requests, so I am looking for a new maintainer. I won't just pick anyone, as people are using the module, so I have to ensure it goes into good hands. If no one suitable comes forward (in a reasonable amount of time) I will deprecate the module in npm and archive the repo in GitHub.

**Comment by roryrjb** [comment]
No one has stepped forward to maintain this project. Closing all issues. I will delete this from GitHub on the 1st May 2020. If you are still interested please step forward and I will transfer the repo or fork or download the code. Thank you for all that found any use with this code!

**Comment by Richienb** [comment]
@roryrjb I also can continue maintaining this along with sha1-file.

**Comment by roryrjb** [comment]
@Richienb thank you again. I have transferred this repo to you and added you as maintainer to the NPM packages for this module and for sha1-file (although the git repo for that is gone, so please feel free to resurrect it again under your name from the NPM package).

**Comment by perugini** [comment]
@Richienb @roryrjb I can help on it, I've updated it to crypto.createCipheriv, and passed the test.

**Comment by Richienb** [comment]
@perugini Great! Create a PR and I'll add you as a collaborator.
